import { test,expect } from '@playwright/test'
test.use({ hasTouch:true })
test.skip(!!process.env.KODIK_TEST_URL,'Android platform simulation uses the development module graph')
test('Android Back hooks: окно, клавиатура, полный редактор, курс и главная',async({page})=>{
  await page.setViewportSize({width:393,height:873})
  // Browser simulation of Capacitor's Android platform; not a physical device.
  await page.addInitScript(()=>{ (window as unknown as {CapacitorCustomPlatform:unknown}).CapacitorCustomPlatform={name:'android'} })
  await page.goto('/')
  const back = () => page.evaluate(async()=>{
    const {handleAndroidBack}=await import('/src/nativeBack.ts');return handleAndroidBack()
  })
  await page.getByRole('button',{name:'Начать бесплатно',exact:true}).click()
  await expect(page.locator('.blocklySvg')).toBeVisible()
  await page.getByRole('button',{name:'Развернуть редактор'}).click()
  await page.getByRole('button',{name:'Добавить блок',exact:true}).click()
  expect(await back()).toBe(true);await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.block-workspace-grid.is-expanded')).toBeVisible()
  expect(await back()).toBe(true);await expect(page.locator('.block-workspace-grid.is-expanded')).toHaveCount(0)
  await page.getByRole('button',{name:'Добавить блок',exact:true}).click()
  await page.getByRole('dialog').locator('.block-options button').filter({has:page.getByText('Напечатать',{exact:true})}).click()
  await page.getByRole('button',{name:'Добавить блок',exact:true}).click()
  await page.getByRole('dialog').locator('.block-options button').filter({has:page.getByText('Текст',{exact:true})}).click()
  await page.locator('.text .blocklyInputField').click()
  await expect(page.getByRole('dialog',{name:'Клавиатура Кодик'})).toBeVisible()
  expect(await back()).toBe(true);await expect(page.getByRole('dialog',{name:'Клавиатура Кодик'})).toHaveCount(0)
  await expect(page.locator('.blocklySvg')).toBeVisible()
  expect(await back()).toBe(true);await expect(page.getByRole('heading',{name:'Python с нуля',exact:true})).toBeVisible()
  expect(await back()).toBe(true);await expect(page.getByRole('button',{name:/Продолжить обучение/})).toBeVisible()
  expect(await back()).toBe(false)
})
