import { test, expect, type Page } from '@playwright/test'
import { lessons } from '../src/course'
import { fillFieldEditor } from './fieldEditor'

async function seed(page: Page, id: number) {
  const prior = lessons.slice(0, lessons.findIndex(lesson => lesson.id === id))
  await page.addInitScript(data => { if (!localStorage.getItem('kodik-progress-v1')) localStorage.setItem('kodik-progress-v1', JSON.stringify(data)) }, { version: 4, completed: prior.map(lesson => lesson.id), currentLesson: id, started: true, bestStars: {}, introducedConcepts: prior.flatMap(lesson => lesson.tutorial || []) })
  await page.goto('/')
}

for (const height of [568, 667, 844]) test(`компоновка главной, карты и Blockly при высоте ${height}`, async ({ page }) => {
  await page.setViewportSize({ width: 390, height })
  await seed(page, 2)
  await page.evaluate(() => document.fonts.ready)
  await expect(page.locator('.bottom-navigation button')).toHaveCount(4)
  await expect(page.locator('.bottom-navigation button svg')).toHaveCount(4)
  expect(await page.locator('.home-path-preview').evaluate(e => e.getBoundingClientRect().bottom <= innerHeight - 70)).toBe(true)
  expect(await page.locator('.home-path-preview li').first().evaluate(e => e.getBoundingClientRect().height)).toBeGreaterThan(40)
  await page.screenshot({ path: `docs/mobile-ux/polish-home-${height}.png` })
  await page.getByRole('button', { name: 'Курс', exact: true }).click()
  const chapter = await page.locator('.chapter-switcher').boundingBox()
  const row = await page.locator('.path-fixed-lessons li').first().boundingBox()
  expect(row!.y - chapter!.y - chapter!.height).toBeGreaterThanOrEqual(10)
  const rows = await page.locator('.path-fixed-lessons li').all()
  for (let i = 1; i < rows.length; i++) {
    const previous = await rows[i - 1].boundingBox(), current = await rows[i].boundingBox()
    expect(current!.y - previous!.y - previous!.height).toBeGreaterThanOrEqual(6)
  }
  await page.screenshot({ path: `docs/mobile-ux/polish-course-${height}.png` })
  await page.getByRole('button', { name: /Продолжить обучение/ }).click()
  await expect(page.locator('.blocklySvg')).toBeVisible()
  const canvas = await page.locator('.blockly-host').boundingBox()
  expect(canvas!.height).toBeGreaterThan(height < 620 ? 190 : 210)
  await page.screenshot({ path: `docs/mobile-ux/polish-blocks-${height}.png` })
  await page.getByRole('button', { name: 'Развернуть редактор' }).click()
  await expect(page.getByRole('button', { name: 'Свернуть редактор' })).toBeVisible()
  expect((await page.locator('.blockly-host').boundingBox())!.height).toBeGreaterThan(canvas!.height + 70)
  await page.getByRole('button', { name: 'Свернуть редактор' }).click()
  await page.mouse.wheel(0, 800)
  expect(await page.evaluate(() => scrollY)).toBe(0)
})

test('ошибки остаются после исправления, средняя оценка и аккаунт сохраняются', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 667 })
  await seed(page, 23)
  await page.getByRole('button', { name: /Продолжить обучение/ }).click()
  await page.getByLabel('Твой Python', { exact: true }).fill('print("Ошибка")')
  await page.getByRole('button', { name: 'Проверить', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Почти получилось', exact: true })).toBeVisible()
  await page.getByLabel('Твой Python', { exact: true }).fill(lessons.find(l => l.id === 23)!.answer!)
  await page.getByRole('button', { name: 'Проверить снова', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Получилось!', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'К карте курса', exact: true }).click()
  await page.getByRole('button', { name: 'Прогресс', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Прогресс', exact: true })).toBeVisible()
  await expect(page.locator('.metric-primary strong')).toContainText('0,0')
  await expect(page.locator('.history-row.is-fixed')).toHaveCount(1)
  await page.screenshot({ path: 'docs/mobile-ux/polish-progress-667.png' })
  await page.locator('.history-row').click()
  await expect(page.getByRole('dialog')).toContainText('Исправлено')
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click()
  await page.getByRole('button', { name: 'Аккаунт', exact: true }).click()
  await page.getByLabel('Как тебя называть?').fill('Мира')
  await page.getByRole('button', { name: 'Сохранить имя' }).click()
  await expect(page.getByRole('heading', { name: 'Мира' })).toBeVisible()
  await page.screenshot({ path: 'docs/mobile-ux/polish-account-667.png' })
  await page.reload()
  await page.getByRole('button', { name: 'Аккаунт', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Мира' })).toBeVisible()
  await page.getByRole('button', { name: 'Прогресс', exact: true }).click()
  await expect(page.locator('.history-row.is-fixed')).toHaveCount(1)
  await expect(page.locator('.metric-primary strong')).toContainText('0,0')
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('kodik-progress-v1')!))
  expect(saved.firstAttemptResults['23'].stars).toBe(0)
  expect(saved.errorHistory).toHaveLength(1)
})

test('блоки переменной и текста доступны в увеличенном мобильном редакторе', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 667 })
  await seed(page, 2)
  await page.getByRole('button', { name: /Продолжить обучение/ }).click()
  const add = async (label: string) => {
    await page.getByRole('button', { name: 'Добавить блок', exact: true }).click()
    await page.getByRole('dialog').locator('.block-options button').filter({ has: page.getByText(label, { exact: true }) }).click()
  }
  await page.getByRole('button', { name: 'Добавить блок', exact: true }).click()
  await page.getByRole('dialog').locator('.variable-option').click()
  await page.getByLabel('Название переменной').fill('имя')
  await page.getByRole('button', { name: 'Создать', exact: true }).click()
  await add('Присвоить')
  await add('Текст')
  await page.locator('.text .blocklyInputField').click()
  await fillFieldEditor(page, 'Мира')
  await add('Напечатать')
  await add('Получить переменную')
  await page.screenshot({ path: 'docs/mobile-ux/polish-blocks-filled-667.png' })
  await page.getByRole('button', { name: 'Проверить', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Получилось!', exact: true })).toBeVisible()
})
