import { test, expect, type Page } from '@playwright/test'
import { lessons } from '../src/course'
async function seed(page: Page, id: number, supportLevel = 'free_code') {
 const prior=lessons.filter(lesson=>lesson.id<id)
 await page.addInitScript(data=>{if(!localStorage.getItem('kodik-progress-v1'))localStorage.setItem('kodik-progress-v1',JSON.stringify(data))},{version:4,completed:prior.map(item=>item.id),currentLesson:id,started:true,bestStars:{},introducedConcepts:prior.flatMap(item=>item.tutorial || []),sessions:{[id]:{attempts:0,hintsUsed:0,solutionUsed:false,startedAt:Date.now(),supportLevel}}})
 await page.goto('/'); await page.getByRole('button',{name:/Продолжить обучение/}).click()
}
test('теория бесплатна, редактор подсвечивает код и вставляет символы с курсором внутри',async({page})=>{
 await page.setViewportSize({width:390,height:667});await seed(page,23)
 await page.getByRole('button',{name:'Разбор темы и пример'}).click();await page.getByRole('button',{name:'Закрыть',exact:true}).click()
 const input=page.getByLabel('Твой Python',{exact:true})
 await input.fill('print');await input.evaluate((e:HTMLTextAreaElement)=>e.setSelectionRange(5,5))
 await page.getByRole('button',{name:'Скобки',exact:true}).click();await expect(input).toHaveValue('print()')
 expect(await input.evaluate((e:HTMLTextAreaElement)=>e.selectionStart)).toBe(6)
 await page.getByRole('button',{name:'Кавычки',exact:true}).click();await expect(input).toHaveValue('print("")')
 expect(await input.evaluate((e:HTMLTextAreaElement)=>e.selectionStart)).toBe(7)
 await page.getByRole('button',{name:'Отступ',exact:true}).click();await expect(input).toHaveValue('print("    ")')
 await input.fill(lessons.find(item=>item.id===23)!.answer!)
 await expect(page.locator('.editor-highlight .syntax-keyword')).toContainText('print')
 await expect(page.locator('.editor-highlight .syntax-string')).toHaveCount(2)
 await page.screenshot({path:'docs/mobile-ux/audit-editor-667.png'})
 await page.getByRole('button',{name:'Проверить',exact:true}).click();await expect(page.locator('.feedback-panel').getByLabel('3 из 3 звёзд')).toBeVisible()
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('kodik-progress-v1')!))
 expect(saved.sessions['23'].hintsUsed).toBe(0);expect(saved.skillStates.string.independentSuccesses).toBeGreaterThan(0)
})
test('две разные ошибки в списке → короткая практика → тот же урок с частями Python',async({page})=>{
 await page.setViewportSize({width:390,height:844});await seed(page,67)
 const input=page.getByLabel('Твой Python',{exact:true})
 await input.fill('print("неверно")');await page.getByRole('button',{name:'Проверить',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Почти получилось',exact:true})).toBeVisible()
 await input.fill('print("другая ошибка")');await page.getByRole('button',{name:'Проверить снова',exact:true}).click()
 await expect(page.getByRole('button',{name:'Закрепить на примере',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Закрепить на примере',exact:true}).click()
 await expect(page.getByRole('article',{name:'Короткая практика',exact:true})).toBeVisible()
 const buttons=page.locator('.token-options button');for(let i=await buttons.count()-1;i>=0;i--)await buttons.nth(i).click()
 await page.getByRole('button',{name:'Проверить',exact:true}).click();await expect(page.getByRole('heading',{name:'Получилось!',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Продолжить',exact:true}).click()
 await expect(page.locator('[data-lesson-id="67"].support-code_tokens')).toBeVisible()
 await expect(page.locator('.blocklySvg')).toHaveCount(0)
 await page.reload();await page.getByRole('button',{name:/Продолжить обучение/}).click()
 await expect(page.locator('[data-lesson-id="67"].support-code_tokens')).toBeVisible()
})
for(const height of [568,667])test(`навыки главное в прогрессе и помещаются при ${height}`,async({page})=>{
 await page.setViewportSize({width:390,height});await page.goto('/')
 await page.getByRole('button',{name:'Прогресс',exact:true}).click()
 await expect(page.getByRole('button',{name:'Навыки',exact:true})).toHaveAttribute('aria-pressed','true')
 await expect(page.locator('.skill-card')).toHaveCount(4)
 const box=await page.locator('.skill-pages').boundingBox(); const nav=await page.locator('.bottom-navigation').boundingBox();expect(box!.y+box!.height).toBeLessThanOrEqual(nav!.y)
 await page.getByRole('button',{name:'Следующие навыки'}).click();await expect(page.locator('.skill-card').first()).toContainText('Переменные')
 await page.screenshot({path:`docs/mobile-ux/audit-skills-${height}.png`})
 expect(await page.evaluate(()=>scrollY)).toBe(0)
})
