import { test, expect, type Page } from '@playwright/test'
import { lessons } from '../src/course'
import { mkdirSync } from 'node:fs'
const add = async (page: Page, name: string) => { await page.getByRole('button',{name:/Добавить блок/}).click(); await page.locator('.block-options button').filter({has:page.getByText(name,{exact:true})}).click() }
const edit = async (page: Page, value: string, index = 0) => { await page.locator('.blocklyInputField').nth(index).click(); await page.locator('.blocklyHtmlInput').fill(value); await page.locator('.blocklyHtmlInput').press('Enter') }
const check = async (page: Page) => { await page.getByRole('button',{name:'Проверить',exact:true}).click(); await expect(page.getByRole('heading',{name:'Получилось!',exact:true})).toBeVisible() }
async function greeting(page: Page, message: string) { await add(page,'Напечатать'); await add(page,'Текст'); await edit(page,message) }

for (const width of [360,390,430,1366]) test(`новичок: первые пять упражнений ${width}`,async ({page}) => {
  await page.setViewportSize({width,height:width === 360 ? 800 : width === 430 ? 932 : width === 1366 ? 768 : 844})
  const errors: string[] = []; page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/'); await page.getByRole('button',{name:/Начать бесплатно/}).click()
  await expect(page.locator('.coach')).toContainText('Шаг 1')
  await expect(page.locator('.blocklyBlockCanvas .blocklyBlock')).toHaveCount(0)
  await page.getByRole('button',{name:/Добавить блок/}).click()
  await expect(page.locator('.block-options button')).toHaveCount(1)
  await page.locator('.block-options button').click()
  await expect(page.locator('.coach')).toContainText('ЧТО показать')
  await expect(page.locator('.live-mirror')).toContainText('print(...)')
  await add(page,'Текст'); await expect(page.locator('.coach')).toContainText('белое поле')
  await edit(page,'Привет!')
  await expect(page.locator('.live-mirror')).toContainText('print("Привет!")')
  await check(page); await expect(page.getByText('Знакомство завершено · без оценки')).toBeVisible()
  await page.getByRole('button',{name:'Продолжить',exact:true}).click()
  await expect(page.locator('.coach')).toHaveCount(0)
  await greeting(page,'Мне нравится Python'); await check(page)
  await expect(page.locator('.feedback-panel').getByLabel('3 из 3 звёзд')).toBeVisible()
  await page.getByRole('button',{name:'Продолжить',exact:true}).click()
  await page.getByRole('radio',{name:'print("Привет!")',exact:true}).check(); await check(page)
  await page.getByRole('button',{name:'Продолжить',exact:true}).click()
  await expect(page.locator('.coach')).toContainText('соединится')
  await add(page,'Напечатать'); await add(page,'Текст'); await edit(page,'Финиш',1); await check(page)
  await page.getByRole('button',{name:'Продолжить',exact:true}).click()
  await greeting(page,'Старт'); await add(page,'Напечатать'); await add(page,'Текст'); await edit(page,'Финиш',1); await check(page)
  await page.getByRole('button',{name:'Продолжить',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Python с нуля',exact:true})).toBeVisible()
  await expect(page.getByRole('button').filter({hasText:'Число или текст?'})).toBeEnabled()
  await page.getByRole('button').filter({hasText:'Научим программу говорить'}).click()
  await expect(page.locator('.coach')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('черновик, шаг обучения и попытки восстанавливаются после перезагрузки',async ({page})=>{
  await page.goto('/'); await page.getByRole('button',{name:/Начать бесплатно/}).click()
  await add(page,'Напечатать')
  await expect(page.locator('.blocklyBlockCanvas .blocklyBlock')).toHaveCount(1)
  expect(await page.evaluate(()=>localStorage.getItem('kodik-progress-v1'))).toContain('text_print')
  await page.reload(); await page.getByRole('button',{name:/Продолжить обучение/}).click()
  await expect(page.locator('.coach')).toContainText('ЧТО показать')
  await add(page,'Текст'); await edit(page,'Привет!'); await check(page); await page.getByRole('button',{name:'Продолжить',exact:true}).click()
  await page.getByRole('button',{name:'Проверить',exact:true}).click(); await page.getByRole('button',{name:'Попробовать снова',exact:true}).click()
  await page.reload(); await page.getByRole('button',{name:/Продолжить обучение/}).click()
  await expect(page.getByRole('heading',{name:'Давай исправим',exact:true})).toBeVisible(); await page.getByRole('button',{name:'Попробовать снова',exact:true}).click()
  await greeting(page,'Мне нравится Python'); await check(page)
  await expect(page.locator('.feedback-panel').getByLabel('2 из 3 звёзд')).toBeVisible()
})

test('подсказка, текст редактора и последний результат проверки восстанавливаются',async ({page})=>{
  const prior = lessons.slice(0,lessons.findIndex(l=>l.id===20))
  await page.addInitScript(data=>{ if (!localStorage.getItem('kodik-progress-v1')) localStorage.setItem('kodik-progress-v1',JSON.stringify(data)) }, {version:2,completed:prior.map(l=>l.id),bestStars:Object.fromEntries(prior.filter(l=>!l.tutorial).map(l=>[l.id,3])),introducedConcepts:prior.flatMap(l=>l.tutorial||[]),currentLesson:20,started:true})
  await page.goto('/'); await page.getByRole('button',{name:/Продолжить обучение/}).click()
  await page.getByRole('button',{name:'Нужна подсказка?'}).click()
  await page.getByLabel('Твой Python',{exact:true}).fill('имя = "Мира\nprint(имя)')
  await page.getByRole('button',{name:'Проверить',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Давай исправим',exact:true})).toBeVisible()
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('kodik-progress-v1')!).sessions?.['20']?.lastCheck?.passed)).toBe(false)
  await page.reload(); await page.getByRole('button',{name:/Продолжить обучение/}).click()
  await expect(page.getByRole('heading',{name:'Давай исправим',exact:true})).toBeVisible()
  await expect(page.locator('.feedback-panel')).toContainText('синтаксис')
  await page.getByRole('button',{name:'Попробовать снова',exact:true}).click()
  await expect(page.getByLabel('Твой Python',{exact:true})).toHaveValue('имя = "Мира\nprint(имя)')
  await expect(page.locator('.hint-text')).toBeVisible()
  await expect(page.locator('.primary-action')).toContainText('Проверок: 1 · подсказок: 1')
})

for(const [width,height] of [[360,800],[375,812],[390,844],[430,932],[768,1024],[1366,768],[1920,1080]]) test(`новый интерфейс ${width}`,async({page})=>{
  mkdirSync('artifacts',{recursive:true}); await page.setViewportSize({width,height}); await page.goto('/'); await page.getByRole('button',{name:/Начать бесплатно/}).click(); await expect(page.locator('.blocklySvg')).toBeVisible()
  await page.screenshot({path:`artifacts/novice-${width}.png`,fullPage:true})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.evaluate(()=>document.querySelector('.add-block-button')!.getBoundingClientRect().bottom <= document.querySelector('.primary-action')!.getBoundingClientRect().top)).toBe(true)
  await page.getByRole('button',{name:/Добавить блок/}).click(); await expect(page.getByRole('dialog')).toBeVisible(); await page.keyboard.press('Escape'); await expect(page.getByRole('button',{name:/Добавить блок/})).toBeFocused()
  await page.getByRole('button',{name:'К карте курса'}).click(); await page.screenshot({path:`artifacts/chapters-${width}.png`,fullPage:true})
})
