import assert from 'node:assert/strict'
import { checkLesson, lessons, renderPython, runProgram, validName, type Expr, type Program, type Stmt } from '../src/learningEngine'
const num = (value: number): Expr => ({ kind: 'number', value })
const str = (value: string): Expr => ({ kind: 'string', value })
const variable = (name: string): Expr => ({ kind: 'variable', name })
const print = (value: Expr): Stmt => ({ kind: 'print', value })
const binary = (operator: '+'|'-'|'*'|'/'|'**', left: Expr, right: Expr): Expr => ({ kind: 'binary', operator, left, right })
const run = (...statements: Stmt[]) => runProgram({ statements })
const output = (expr: Expr) => run(print(expr)).output
assert.deepEqual(output(binary('*', binary('+', num(2), num(3)), num(4))), ['20'])
assert.equal(renderPython({ statements: [print(binary('*', binary('+', num(2), num(3)), num(4)))] }), 'print((2 + 3) * 4)')
assert.deepEqual(output(binary('/', num(6), num(2))), ['3.0'])
assert.deepEqual(output(binary('+', binary('/', num(6), num(2)), num(2))), ['5.0'])
assert.deepEqual(output(binary('**', num(-2), num(2))), ['4'])
assert.equal(renderPython({ statements: [print(binary('**', num(-2), num(2)))] }), 'print((-2) ** 2)')
assert.match(run(print(binary('/', num(1), num(0)))).error!, /ноль/)
assert.match(run(print(binary('+', str('2'), num(3)))).error!, /два числа/)
assert.match(run(print(variable('нет'))).error!, /Сначала сохрани/)
assert.match(run(print({ kind: 'missing' })).error!, /пустое место/)
assert.deepEqual(output({ kind: 'comparison', operator: '>=', left: num(12), right: num(10) }), ['True'])
assert.deepEqual(output({ kind: 'comparison', operator: '<', left: num(12), right: num(10) }), ['False'])
assert.deepEqual(run({ kind: 'repeat', times: num(-1), body: [print(str('no'))] }).output, [])
assert.match(run({ kind: 'repeat', times: num(1.5), body: [] }).error!, /целым/)
assert.match(run({ kind: 'repeat', times: binary('/', num(6), num(2)), body: [] }).error!, /целым/)
assert.match(run({ kind: 'repeat', times: num(1e9), body: [] }).error!, /повторений/)
assert.match(run(print(binary('**', num(10), num(10000)))).error!, /большой/)
assert.match(run(print(str('x'.repeat(2001)))).error!, /длинный/)
const condition: Program = { statements: [
  { kind: 'assign', name: 'x', value: num(1) },
  { kind: 'if', condition: variable('x'), then: [{ kind: 'assign', name: 'x', value: num(0) }, print(str('then'))], otherwise: [print(str('else'))] }
] }
assert.deepEqual(runProgram(condition).output, ['then'], 'Must choose the branch once before executing it')
assert.deepEqual(run({ kind: 'if', condition: binary('/', num(0), num(1)), then: [print(str('bad'))], otherwise: [print(str('ok'))] }).output, ['ok'])
assert.deepEqual(run({ kind: 'define', name: 'hello', body: [print(str('hello'))] }, { kind: 'call', name: 'hello' }).output, ['hello'])
assert.deepEqual(run({ kind: 'define', name: 'hello', body: [print(str('hello'))] }).output, [])
assert.match(run({ kind: 'call', name: 'hello' }).error!, /Сначала создай/)
assert.match(run({ kind: 'define', name: 'f', body: [{ kind: 'call', name: 'f' }] }, { kind: 'call', name: 'f' }).error!, /слишком/)
assert.equal(checkLesson(lessons[2], { statements: [print(binary('+', num(3), num(2)))] }).passed, true)
assert.equal(checkLesson(lessons[2], { statements: [print(num(5))] }).passed, false, 'Hardcoded output does not teach arithmetic')
assert.equal(validName('ёлка'), true)
for (const name of ['if','print','range','2a','a b','a-b','__kodik_repeat']) assert.equal(validName(name), false)
assert.equal(run(print(binary('/', num(1), num(0)))).systemError, false)
assert.equal(run({ kind: 'print', value: null } as unknown as Stmt).systemError, true)
console.log('✓ 36 регрессионных проверок: порядок, числа, типы, условия, функции, лимиты, безопасные имена и альтернативные решения.')
