export const solutionReferences: Record<number, string> = {
  1: 'print("Привет, Кодик!")',
  2: 'print("Меня зовут Алекс")',
  3: 'print("Старт")\nprint("Поехали!")',
  4: 'print(\'Python говорит: "Привет!"\')',
  5: 'print("Код" + "ик")',
  6: 'print("1")\nprint("2")\nprint("3")',
  7: 'print("Привет")',
  8: 'print("Привет!")\nprint("Я учусь программировать")\nprint("До встречи!")',
  9: 'print(2026)',
  10: 'print(7 + 5)',
  11: 'print(20 - 8)',
  12: 'print(6 * 4)',
  13: 'print(20 / 4)',
  14: 'print((2 + 3) * 4)',
  15: 'print(3 * 5)',
  16: 'print((10 + 2) * 3 - 4)',
  17: 'name = "Аня"\nprint(name)',
  18: 'age = 12\nprint(age)',
  19: 'score = 5\nscore = 8\nprint(score)',
  20: 'a = 4\nb = 7\nprint(a + b)',
  21: 'money = 10\nmoney = money + 5\nprint(money)',
  22: 'name = "Миша"\nprint("Привет, " + name + "!")',
  23: 'x = 2\nx = x + 3\nx = x * 2\nprint(x)',
  24: 'name = "Лея"\nage = 14\nlevel = 3\nprint(name)\nprint(age)\nprint(level)',
  25: 'name = "Кодик"\nprint(name)',
  26: 'name = "Аня"\nprint(name)',
  27: 'city = "Минск"\nprint(city)',
  28: 'print(2 + 3)',
  29: 'name = "Лена"\nprint(name)',
  30: 'x = 1\ny = 3\nx = y + 2\ny = 10\nprint(x)',
  31: 'name = "Кодик"\nscore = 5\nprint(name)\nprint(score)',
  32: 'item = "Сок"\nprice = 4\ncount = 3\ntotal = price * count\nprint(item)\nprint(total)',
  33: 'print(8 > 5)',
  34: 'print(3 < 1)',
  35: 'print(10 == 10)',
  36: 'print(7 != 4)',
  37: 'age = 18\nprint(age >= 18)',
  38: 'a = 12\nb = 15\nprint(a < b)',
  39: 'print(5 == 5)\nprint(2 > 9)\nprint(7 != 7)',
  40: 'temperature = -1\nprint(temperature < 0)',
  41: 'age = 20\nif age >= 18:\n    print("Можно")',
  42: 'temperature = 5\nif temperature < 0:\n    print("Мороз")',
  43: 'is_raining = False\nif is_raining:\n    print("Бери зонт")\nelse:\n    print("Зонт не нужен")',
  44: 'x = -3\nif x > 0:\n    print("Положительное")\nelse:\n    print("Не положительное")',
  45: 'password = "python"\nif password == "python":\n    print("Доступ")\nelse:\n    print("Ошибка")',
  46: 'age = 16\nif age >= 18:\n    print("18+")\nelse:\n    print("До 18")',
  47: 'score = 82\nif score >= 90:\n    print("Отлично")\nelif score >= 70:\n    print("Хорошо")\nelse:\n    print("Попробуй ещё")',
  48: 'color = "yellow"\nif color == "red":\n    print("Стой")\nelif color == "yellow":\n    print("Жди")\nelse:\n    print("Иди")',
  49: 'age = 20\nif age >= 18:\n    print("Можно")',
  50: 'age = 13\nif age <= 12:\n    price = 5\nelse:\n    price = 8\nprint(price)',
  51: 'for i in range(3):\n    print("Я учусь")',
  52: 'for i in range(5):\n    print(i)',
  53: 'for i in range(1, 6):\n    print(i)',
  54: 'for i in range(1, 5):\n    print(i * i)',
  55: 'for i in range(1, 4):\n    print("Попытка " + str(i))',
  56: 'for i in range(1, 6):\n    print(5 * i)',
  57: 'word = "Кодик"\nfor i in range(4):\n    print(word)',
  58: 'for i in range(1, 6):\n    print(i)',
  59: 'for i in range(1, 6):\n    if i > 3:\n        print(i)',
  60: 'for i in range(5, 0, -1):\n    print(i)',
  61: 'total = 0\nfor i in range(1, 6):\n    total = total + i\nprint(total)',
  62: 'count = 0\nfor i in range(1, 7):\n    if i % 2 == 0:\n        count = count + 1\nprint(count)',
  63: 'i = 1\nwhile i <= 3:\n    print(i)\n    i = i + 1',
  64: 'i = 3\nwhile i >= 1:\n    print(i)\n    i = i - 1',
  65: 'i = 1\ntotal = 0\nwhile i <= 4:\n    total = total + i\n    i = i + 1\nprint(total)',
  66: 'count = 0\nfor i in range(1, 9):\n    if i > 5:\n        count = count + 1\nprint(count)',
  67: 'for row in range(2):\n    line = ""\n    for column in range(3):\n        line = line + "*"\n    print(line)',
  68: 'for i in range(1, 7):\n    if i % 3 == 0:\n        print("Три")\n    else:\n        print(i)',
  69: 'def hello():\n    print("Привет!")\nhello()',
  70: 'def ping():\n    print("Пинг")\nping()\nping()',
  71: 'def greet(name):\n    print(name)\ngreet("Аня")',
  72: 'def add(a, b):\n    print(a + b)\nadd(3, 4)',
  73: 'def double(x):\n    return x * 2\nprint(double(5))',
  74: 'def sum2(a, b):\n    return a + b\nresult = sum2(8, 2)\nprint(result)',
  75: 'def is_adult(age):\n    if age >= 18:\n        return True\n    else:\n        return False\nprint(is_adult(20))',
  76: 'def repeat(word, n):\n    for i in range(n):\n        print(word)\nrepeat("Hi", 3)',
  77: 'def square(x):\n    return x * x\nprint(square(4))',
  78: 'def calc(a, b, op):\n    if op == "+":\n        return a + b\n    elif op == "-":\n        return a - b\n    else:\n        return 0\nprint(calc(10, 3, "-"))',
  79: 'colors = ["red", "green", "blue"]\nprint(colors)',
  80: 'animals = ["кот", "пёс", "лиса"]\nprint(animals[0])',
  81: 'nums = [10, 20, 30]\nprint(nums[2])',
  82: 'fruits = ["яблоко", "груша"]\nfruits[1] = "банан"\nprint(fruits)',
  83: 'print(len([4, 7, 9, 1]))',
  84: 'names = ["Аня", "Боря", "Вика"]\nfor name in names:\n    print(name)',
  85: 'total = 0\nfor number in [2, 4, 6]:\n    total = total + number\nprint(total)',
  86: 'prices = [5, 12, 3, 9]\nbiggest = prices[0]\nfor price in prices:\n    if price > biggest:\n        biggest = price\nprint(biggest)',
  87: 'name = input("Как тебя зовут? ")\nprint("Привет, " + name + "!")',
  88: 'age = int(input("Сколько тебе лет? "))\nprint(age + 1)',
  89: 'a = int(input("Первое число: "))\nb = int(input("Второе число: "))\nprint(a + b)',
  90: 'age = int(input("Возраст: "))\nif age >= 18:\n    print("Вход разрешён")\nelse:\n    print("Вход запрещён")',
  91: 'n = int(input("Сколько раз? "))\nfor i in range(n):\n    print("Кодик")',
  92: 'answer = int(input("Сколько будет 3*4? "))\nif answer == 12:\n    print("Верно!")\nelse:\n    print("Попробуй ещё")',
  93: 'forward(100)',
  94: 'forward(80)\nright(90)\nforward(80)',
  95: 'for i in range(4):\n    forward(60)\n    right(90)',
  96: 'for i in range(3):\n    forward(80)\n    right(120)',
  97: 'size = 50\nfor i in range(4):\n    forward(size)\n    right(90)',
  98: 'sides = 6\nsize = 40\nangle = 360 / sides\nfor i in range(sides):\n    forward(size)\n    right(angle)',
  99: 'def draw_square(size):\n    for i in range(4):\n        forward(size)\n        right(90)\ndraw_square(70)',
  100: 'size = 80\ndef draw_square(side):\n    for i in range(4):\n        forward(side)\n        right(90)\ndraw_square(size)\nforward(size)\nleft(120)\nforward(size)\nleft(120)\nforward(size)',
}
