import { lessons as original, type Lesson, type Program, type Stmt } from './learningEngine'

type Block = { type: string; fields?: Record<string, unknown>; inputs?: Record<string, { block: Block }>; next?: { block: Block }; extraState?: object; x?: number; y?: number }
const text = (value: string): Block => ({ type: 'text', fields: { TEXT: value } })
const number = (value: number): Block => ({ type: 'math_number', fields: { NUM: value } })
const print = (value?: Block): Block => ({ type: 'text_print', inputs: value ? { TEXT: { block: value } } : {} })
const compare = (op: string, a: Block, b: Block): Block => ({ type: 'logic_compare', fields: { OP: op }, inputs: { A: { block: a }, B: { block: b } } })
const math = (op: string, a: Block, b: Block): Block => ({ type: 'math_arithmetic', fields: { OP: op }, inputs: { A: { block: a }, B: { block: b } } })
const chain = (...blocks: Block[]): Block => blocks.reduceRight((next, block) => ({ ...block, ...(next ? { next: { block: next } } : {}) }), undefined as unknown as Block)
const state = (...blocks: Block[]) => ({ blocks: { languageVersion: 0, blocks: blocks.map((block, i) => ({ ...block, x: 24, y: 32 + i * 150 })) } })
const walk = (statements: Stmt[]): Stmt[] => statements.flatMap(s => [s, ...('body' in s ? walk(s.body) : s.kind === 'if' ? [...walk(s.then), ...walk(s.otherwise)] : [])])
const requires = (kind: Stmt['kind'], message: string) => (p: Program) => walk(p.statements).some(s => s.kind === kind) ? null : message
const define = (body?: Block): Block => ({ type: 'kodik_define', fields: { NAME: 'приветствие' }, inputs: body ? { BODY: { block: body } } : {} })
const call = (): Block => ({ type: 'kodik_call', fields: { NAME: 'приветствие' } })

const added: Lesson[] = [
  { id: 6, kicker: 'Значения и строки', title: 'Число или текст?', instruction: 'Число можно использовать в вычислениях. Текст записывается в кавычках. Python печатает оба значения, но хранит их по-разному.', goal: 'Выведи число 7, а на следующей строке — текст «семь».', starterHint: 'Добавь текст в пустое место второго блока печати.', hint: 'Нажми «Добавить блок» → «Текст». Впиши «семь». Порядок блоков задаёт порядок строк.', expectedOutput: ['7', 'семь'], starter: state(chain(print(number(7)), print())), solution: state(chain(print(number(7)), print(text('семь')))), validate: p => p.statements.some(s => s.kind === 'print' && s.value.kind === 'number') && p.statements.some(s => s.kind === 'print' && s.value.kind === 'string') ? null : 'Используй число в первой печати и текст во второй.', success: '7 — число, а «семь» — строка. Два блока print выполняются сверху вниз.' },
  { id: 7, kicker: 'Порядок действий', title: 'Сначала — начало', instruction: 'Python выполняет команды по порядку, сверху вниз. Каждая печать добавляет новую строку.', goal: 'Напечатай «Старт», затем «Финиш».', starterHint: 'Начни с блока «Напечатать». Добавляй команды по очереди.', hint: 'Добавь две печати. Текст первой — «Старт», второй — «Финиш».', expectedOutput: ['Старт', 'Финиш'], starter: state(), solution: state(chain(print(text('Старт')), print(text('Финиш')))), validate: requires('print', 'Добавь печать сообщения.'), success: 'Сначала выполнилась первая печать, затем вторая. Порядок команд меняет результат программы.' },
  { id: 8, kicker: 'Вычисления', title: 'Скобки имеют значение', instruction: 'Вложенный блок вычисляется первым. Это соответствует скобкам в Python.', goal: 'Сложи 2 и 3, затем умножь сумму на 4. Получи 20.', starterHint: 'Измени знак внешнего вычисления: нужно умножение.', hint: 'Открой список знаков в большом блоке и выбери ×. Внутренний блок 2 + 3 оставь как есть.', expectedOutput: ['20'], starter: state(print(math('ADD', math('ADD', number(2), number(3)), number(4)))), solution: state(print(math('MULTIPLY', math('ADD', number(2), number(3)), number(4)))), validate: p => p.statements.some(s => s.kind === 'print' && s.value.kind === 'binary' && s.value.operator === '*' && (s.value.left.kind === 'binary' || s.value.right.kind === 'binary')) ? null : 'Умножь вложенную сумму с помощью блока вычисления.', success: 'Сначала 2 + 3 = 5. Затем 5 × 4 = 20. В Python порядок сохраняют скобки: (2 + 3) * 4.' },
  { id: 9, kicker: 'Сравнения', title: 'Правда или нет?', instruction: 'Сравнение даёт True (истина) или False (ложь). Знак ≥ означает «больше или равно».', goal: 'Проверь, что 12 не меньше 10, и напечатай результат сравнения.', starterHint: 'Измени знак = в блоке сравнения на ≥.', hint: 'Равенство спрашивает, одинаковы ли числа. Здесь нужно «больше или равно».', expectedOutput: ['True'], starter: state(print(compare('EQ', number(12), number(10)))), solution: state(print(compare('GTE', number(12), number(10)))), validate: p => p.statements.some(s => s.kind === 'print' && s.value.kind === 'comparison' && ((s.value.operator === '>=' && s.value.left.kind === 'number' && s.value.left.value === 12 && s.value.right.kind === 'number' && s.value.right.value === 10) || (s.value.operator === '<=' && s.value.left.kind === 'number' && s.value.left.value === 10 && s.value.right.kind === 'number' && s.value.right.value === 12))) ? null : '12 и 10 не равны. Проверь, что 12 не меньше 10: это верно и для 11, 12, 13…', success: '12 ≥ 10 — истина. В Python такая проверка записывается как 12 >= 10 и возвращает True.' },
  { id: 10, kicker: 'Условия', title: 'А если нет?', instruction: 'Ветка «иначе» выполняется, когда условие ложно. Программа выбирает только одну из двух веток.', goal: 'Проверь 3 ≥ 10. Если верно, напечатай «Можно», иначе — «Пока рано».', starterHint: 'Ветка «иначе» пока пустая. Добавь в неё печать текста.', hint: 'Выбери блок «если», затем добавь печать. Она заполнит пустую ветку. Впиши «Пока рано».', expectedOutput: ['Пока рано'], starter: state({ type: 'controls_if', extraState: { hasElse: true }, inputs: { IF0: { block: compare('GTE', number(3), number(10)) }, DO0: { block: print(text('Можно')) } } }), solution: state({ type: 'controls_if', extraState: { hasElse: true }, inputs: { IF0: { block: compare('GTE', number(3), number(10)) }, DO0: { block: print(text('Можно')) }, ELSE: { block: print(text('Пока рано')) } } }), validate: p => p.statements.some(s => s.kind === 'if' && s.otherwise.length) ? null : 'Добавь действие в ветку «иначе».', success: '3 меньше 10, поэтому условие ложно. Python пропустил первую ветку и выполнил else.' },
  { id: 11, kicker: 'Функции', title: 'Дай действию имя', instruction: 'Функция объединяет команды под одним именем. Определение запоминает команды, а вызов выполняет их.', goal: 'Создай функцию «приветствие», печатающую «Привет!», и вызови её один раз.', starterHint: 'Функция уже описана. Добавь блок «Вызвать функцию».', hint: 'В разделе «Функции» выбери вызов. Имя в нём должно совпадать с именем определения.', expectedOutput: ['Привет!'], starter: state(define(print(text('Привет!')))), solution: state(chain(define(print(text('Привет!'))), call())), validate: p => walk(p.statements).some(s => s.kind === 'define') && walk(p.statements).some(s => s.kind === 'call') ? null : 'Одного определения мало: добавь вызов функции.', success: 'def запоминает команды функции. Строка приветствие() вызывает их и печатает сообщение.' },
  { id: 12, kicker: 'Финальная практика', title: 'Одна функция — три привета', instruction: 'Теперь соедини знакомые идеи: функция хранит действие, а цикл повторяет её вызов.', goal: 'Создай функцию «приветствие», которая печатает «Привет!». Вызови её в цикле 3 раза.', starterHint: 'Сначала опиши функцию, затем добавь цикл и помести вызов внутрь.', hint: 'Порядок: определение функции с печатью → повторить 3 раза → внутри цикла вызвать «приветствие».', expectedOutput: ['Привет!', 'Привет!', 'Привет!'], starter: state(), solution: state(chain(define(print(text('Привет!'))), { type: 'controls_repeat_ext', inputs: { TIMES: { block: number(3) }, DO: { block: call() } } })), validate: p => { const all = walk(p.statements); return all.some(s => s.kind === 'define') && all.some(s => s.kind === 'repeat' && walk(s.body).some(c => c.kind === 'call')) ? null : 'Опиши функцию, а её вызов помести внутрь цикла.' }, success: 'Ты объединил функцию и цикл в настоящую программу. Теперь ты знаешь вывод, значения, переменные, вычисления, сравнения, условия, циклы и функции.' }
]

const order = [1, 6, 7, 2, 3, 8, 9, 5, 10, 4, 11, 12]
const base = ['text_print', 'text', 'math_number']
export const lessons: Lesson[] = order.map((id, index) => {
  const lesson = [...original, ...added].find(l => l.id === id)!
  const allowed = [...base, ...(index >= 3 ? ['variables_set', 'variables_get'] : []), ...(index >= 4 ? ['math_arithmetic'] : []), ...(index >= 6 ? ['logic_compare'] : []), ...(index >= 7 ? ['controls_if'] : []), ...(index >= 9 ? ['controls_repeat_ext'] : []), ...(index >= 10 ? ['kodik_define', 'kodik_call'] : [])]
  if (id === 1) allowed.splice(2, 1)
  return { ...lesson, allowed,
    ...(id === 2 ? { hint: 'Нажми «Добавить блок» → «Получить переменную». Блок «имя» вставится в пустую печать.' } : {}),
    ...(id === 5 ? { starterHint: 'Собери программу с переменной и условием. Начни с «Присвоить».', hint: 'Создай переменную «баллы», добавь присваивание 12, затем «Если». В условие вставь сравнение, а внутрь — печать.' } : {}) }
})
