import type { SkillId, LessonSkills } from './skills'

type Objective = { skills: LessonSkills; rules: string[] }
// Each row names the evidence this task actually measures. Prerequisites do
// not receive mastery credit merely because they belong to the same chapter.
const rows: [number, SkillId, string, string, string][] = [
  [23,'string','','print','op:+'],
  [24,'arithmetic','variable','number','assign:1 op:*'],
  [25,'arithmetic','variable','number','assign:2 op:-'],
  [26,'variable','string','print,string','assign:1 op:+'],
  [27,'arithmetic','','number','sum_product'],
  [28,'arithmetic','','number','op:+ op:/'],
  [29,'comparison','arithmetic','number','op:% op:=='],
  [30,'sequence','print','print','print:2'],
  [31,'assignment','arithmetic','variable','reassign op:+'],
  [32,'comparison','variable','number','assign:1 op:>='],
  [33,'arithmetic','variable','number','assign:2 op:*'],
  [34,'if','comparison','variable','kind:if branches:1 else op:<'],
  [35,'comparison','if','variable','kind:if op:>='],
  [36,'if','comparison','variable','kind:if else op:>='],
  [37,'if','comparison','string','kind:if op:=='],
  [38,'if','comparison','comparison','branches:2 else'],
  [39,'if','arithmetic','comparison','kind:if else op:%'],
  [40,'if','comparison','comparison','kind:if else op:>='],
  [41,'comparison','if','comparison','kind:if op:and'],
  [42,'if','comparison','comparison','branches:2 else'],
  [43,'if','string','comparison','kind:if else op:=='],
  [44,'if','arithmetic','comparison','kind:if else op:* op:-'],
  [45,'loop','','print','kind:for'],
  [46,'loop','','number','kind:for call:range'],
  [47,'loop','','number','kind:for call:range'],
  [48,'loop','arithmetic,assignment','variable','kind:for reassign op:+'],
  [49,'loop','assignment','variable','kind:for reassign op:+'],
  [50,'loop','comparison,assignment','variable','kind:while reassign'],
  [51,'loop','comparison,assignment','variable','kind:while op:-'],
  [52,'loop','arithmetic','number','kind:for op:*'],
  [53,'loop','arithmetic','loop','nested_loop'],
  [54,'loop','if,arithmetic','if','kind:for kind:if op:%'],
  [55,'loop','arithmetic','variable','kind:for op:* op:+'],
  [56,'function','','sequence','kind:function'],
  [57,'function','string','string','params:1'],
  [58,'function','arithmetic','arithmetic','params:1 kind:return'],
  [59,'function','arithmetic','arithmetic','params:1 kind:return'],
  [60,'function','comparison','comparison','params:1 kind:return op:>='],
  [61,'function','arithmetic','arithmetic','params:2 kind:return'],
  [62,'function','string','string','params:1 kind:return op:+'],
  [63,'function','loop,arithmetic','loop','params:1 kind:return kind:for'],
  [64,'function','comparison,arithmetic','comparison','params:1 kind:return op:%'],
  [65,'function','if,arithmetic','if','params:2 kind:return kind:if'],
  [66,'function','string','string','params:1'],
  [67,'list','','variable','kind:list kind:index'],
  [68,'list','','variable','kind:list kind:index'],
  [69,'list','','variable','kind:list call:len'],
  [70,'list','','variable','kind:list kind:index'],
  [71,'list','loop','loop','kind:list kind:for'],
  [72,'list','loop,arithmetic','loop','kind:list kind:for op:+'],
  [73,'list','loop,comparison','loop,if','kind:list kind:for kind:if'],
  [74,'list','assignment','variable','kind:list mutate_index'],
  [75,'list','loop,if','loop,if','kind:list kind:for kind:if op:%'],
  [76,'list','loop,if','loop,if','kind:list kind:for kind:if'],
  [77,'list','loop,assignment','loop','kind:list kind:for reassign'],
  [78,'list','loop,arithmetic','loop','kind:list kind:for call:len op:+'],
  [79,'input','string','variable','call:input'],
  [80,'input','arithmetic','arithmetic','call:input call:int op:+'],
  [81,'input','arithmetic','arithmetic','input:2 call:int op:+'],
  [82,'input','arithmetic','arithmetic','input:2 call:int op:*'],
  [83,'input','if,comparison','if','call:input call:int kind:if'],
  [84,'input','if,string','if','call:input kind:if'],
  [85,'input','if,comparison','if','call:input call:int kind:if'],
  [86,'input','loop','loop','call:input kind:for'],
  [87,'input','loop','loop','call:input call:int kind:for'],
  [88,'input','arithmetic','arithmetic','input:2 call:int op:-'],
  [89,'input','arithmetic,sequence','arithmetic','input:3 call:int op:* print:2'],
  [90,'drawing','','number','call:forward'],
  [91,'drawing','sequence','sequence','call:forward call:right'],
  [92,'drawing','loop','loop','call:forward kind:for'],
  [93,'drawing','loop','loop','call:forward kind:for'],
  [94,'drawing','loop','loop','call:forward kind:for'],
  [95,'drawing','loop','loop','call:forward kind:for'],
  [96,'drawing','variable,loop','loop,variable','call:forward kind:for assign:1'],
  [97,'drawing','loop','loop','call:forward kind:for call:left'],
  [98,'drawing','function,loop','function,loop','call:forward params:1 kind:for'],
  [99,'drawing','function,loop','function,loop','call:forward kind:function nested_loop'],
  [100,'drawing','function,loop','function,loop','call:forward params:1 kind:for'],
]
const ids = (text: string) => text ? text.split(',') as SkillId[] : []
export const lessonObjectives: Record<number, Objective> = Object.fromEntries(rows.map(([id, primarySkill, practice, prerequisites, rules]) => [id, { skills: { primarySkill, teaches: [primarySkill], practices: ids(practice), requires: ids(prerequisites) }, rules: rules.split(' ') }]))
